/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baithuchanhso2;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class StudentGUI extends javax.swing.JFrame 
{

    String gt = "Nam";
    SV sv;
    int kt = 0, i = 0, stt = 1, t = 0;
//    ArrayList<SV> dssv = new ArrayList<SV>();
    ArrayList<String> dssv = new ArrayList<String>();
    public StudentGUI() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        txtNamsinh = new javax.swing.JTextField();
        CBnu = new javax.swing.JRadioButton();
        CBnam = new javax.swing.JRadioButton();
        Bthem = new javax.swing.JButton();
        Bnapvao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTdssv = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Man");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Giới tính:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Họ tên:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Năm sinh:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtHoten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 150, -1));

        txtNamsinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtNamsinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        buttonGroup1.add(CBnu);
        CBnu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBnu.setText("Nữ");
        CBnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBnuActionPerformed(evt);
            }
        });
        jPanel1.add(CBnu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 60, 20));

        buttonGroup1.add(CBnam);
        CBnam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBnam.setSelected(true);
        CBnam.setText("Nam");
        CBnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBnamActionPerformed(evt);
            }
        });
        jPanel1.add(CBnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 60, 20));

        Bthem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bthem.setText("Thêm");
        Bthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthemActionPerformed(evt);
            }
        });
        jPanel1.add(Bthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 320, 180));

        Bnapvao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bnapvao.setText("Nạp vào");
        Bnapvao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnapvaoActionPerformed(evt);
            }
        });
        jPanel2.add(Bnapvao, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        TXTdssv.setEditable(false);
        TXTdssv.setColumns(20);
        TXTdssv.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        TXTdssv.setRows(5);
        TXTdssv.setText("STT --- HỌ TÊN ------------- NĂM SINH ------ GIỚI TÍNH\n");
        jScrollPane1.setViewportView(TXTdssv);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 450, 200));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBnamActionPerformed
        // TODO add your handling code here:
        gt = "Nam";
    }//GEN-LAST:event_CBnamActionPerformed

    private void CBnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBnuActionPerformed
        // TODO add your handling code here:
        gt = "Nữ";
    }//GEN-LAST:event_CBnuActionPerformed

    private void BthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthemActionPerformed
        // TODO add your handling code here:
        t = 1;
        if((txtHoten.getText().equals("") || txtHoten.getText().equals(null)) 
                || (txtNamsinh.getText().equals("") || txtNamsinh.getText().equals(null))) 
            JOptionPane.showConfirmDialog(this, "Không thể thêm dữ liệu Rỗng","Cảnh báo!",JOptionPane.WARNING_MESSAGE);
        else
        {
            i = dssv.size();
            sv = new SV(txtHoten.getText(), txtNamsinh.getText(), gt);
            if(dssv.contains(sv.getht() + sv.getns() + sv.getgt()) == true)
            {
                JOptionPane.showMessageDialog(this, "Dữ liệu đã tồn tại!","Lỗi thêm dữ liệu",JOptionPane.WARNING_MESSAGE);
                kt = 1;
            }
            else kt = 0;
            if(kt == 0) dssv.add(sv.getht() + sv.getns() + sv.getgt());
        }
    }//GEN-LAST:event_BthemActionPerformed

    private void BnapvaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnapvaoActionPerformed
        // TODO add your handling code here:
        if(dssv.size() !=0 && stt <= dssv.size() && t == 1 ) 
        {
           TXTdssv.append("\n" + sv.xuat(String.valueOf(stt)));
           stt++;
           t = 0;
        }
        else if(dssv.size() == 0 ) 
            JOptionPane.showMessageDialog(this, "Dữ liệu rỗng!","Lỗi nạp dữ liệu",JOptionPane.WARNING_MESSAGE);
        else if(stt > dssv.size() || t == 0) 
            JOptionPane.showMessageDialog(this, "Dữ liệu đã tồn tại!","Lỗi nạp dữ liệu",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_BnapvaoActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bnapvao;
    private javax.swing.JButton Bthem;
    private javax.swing.JRadioButton CBnam;
    private javax.swing.JRadioButton CBnu;
    private javax.swing.JTextArea TXTdssv;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtNamsinh;
    // End of variables declaration//GEN-END:variables
}
