/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App_Calculator;

import static java.lang.Math.*;

/**
 *
 * @author Phan Minh Quân
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    
    int kt = 0, ktt = 0;
    int kta = 0, ktb = 0, ktc = 0, ktd = 0, kte = 0, ktf =0;
    int ktpt = 0;
            
    public Calculator() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Bthuong = new javax.swing.JButton();
        Bmod = new javax.swing.JButton();
        Btich = new javax.swing.JButton();
        Bhieu = new javax.swing.JButton();
        Btong = new javax.swing.JButton();
        txtA = new javax.swing.JTextField();
        LbA = new javax.swing.JLabel();
        LbKq = new javax.swing.JLabel();
        txtKq = new javax.swing.JTextField();
        LbF = new javax.swing.JLabel();
        txtF = new javax.swing.JTextField();
        LbE = new javax.swing.JLabel();
        txtE = new javax.swing.JTextField();
        LbC = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();
        txtD = new javax.swing.JTextField();
        LbA3 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        LbB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPheptoan = new javax.swing.JTextField();
        txtKq2 = new javax.swing.JTextField();
        txtKq1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtSoNg = new javax.swing.JTextField();
        txtKq3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BXoa = new javax.swing.JButton();
        BThoat = new javax.swing.JButton();
        Bptb2 = new javax.swing.JButton();
        BAns = new javax.swing.JButton();
        BGiai = new javax.swing.JButton();
        Btinh = new javax.swing.JButton();
        Bptb3 = new javax.swing.JButton();
        Bluy = new javax.swing.JButton();
        Bcan = new javax.swing.JButton();
        Bptb4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Máy tính Calculator");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));

        jLabel1.setBackground(new java.awt.Color(200, 194, 194));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MÁY TÍNH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Nhập", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bthuong.setText("/");
        Bthuong.setToolTipText("Chọn phép tính Thương");
        Bthuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthuongActionPerformed(evt);
            }
        });
        jPanel2.add(Bthuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 50, -1));

        Bmod.setText("%");
        Bmod.setToolTipText("Chọn phép tính Thương lấy phần dư");
        Bmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodActionPerformed(evt);
            }
        });
        jPanel2.add(Bmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 110, -1));

        Btich.setText("*");
        Btich.setToolTipText("Chọn phép tính Tích");
        Btich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtichActionPerformed(evt);
            }
        });
        jPanel2.add(Btich, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 50, -1));

        Bhieu.setText("-");
        Bhieu.setToolTipText("Chọn phép tính Hiệu");
        Bhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhieuActionPerformed(evt);
            }
        });
        jPanel2.add(Bhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 50, -1));

        Btong.setText("+");
        Btong.setToolTipText("Chọn phép tính Tổng");
        Btong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtongActionPerformed(evt);
            }
        });
        jPanel2.add(Btong, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 50, -1));

        txtA.setToolTipText("Nhập hệ số A");
        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });
        jPanel2.add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, -1));

        LbA.setText("A:");
        jPanel2.add(LbA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 20, 24));

        LbKq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbKq.setText("Kết quả:");
        jPanel2.add(LbKq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, -1));

        txtKq.setEditable(false);
        txtKq.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtKq.setToolTipText("Kết quả / Nghiệm 1");
        txtKq.setEnabled(false);
        txtKq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKqActionPerformed(evt);
            }
        });
        jPanel2.add(txtKq, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 70, 30));

        LbF.setText("F:");
        jPanel2.add(LbF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 20, 24));

        txtF.setToolTipText("Nhập hệ số F");
        txtF.setEnabled(false);
        txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFActionPerformed(evt);
            }
        });
        jPanel2.add(txtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 90, -1));

        LbE.setText("E:");
        jPanel2.add(LbE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 20, 24));

        txtE.setToolTipText("Nhập hệ số E");
        txtE.setEnabled(false);
        txtE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEActionPerformed(evt);
            }
        });
        jPanel2.add(txtE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 90, -1));

        LbC.setText("C:");
        jPanel2.add(LbC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 30, 24));

        txtC.setToolTipText("Nhập hệ số C");
        txtC.setEnabled(false);
        txtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCActionPerformed(evt);
            }
        });
        jPanel2.add(txtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, -1));

        txtD.setToolTipText("Nhập hệ số D");
        txtD.setEnabled(false);
        txtD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDActionPerformed(evt);
            }
        });
        jPanel2.add(txtD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 90, -1));

        LbA3.setText("D:");
        jPanel2.add(LbA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 20, 24));

        txtB.setToolTipText("Nhập hệ số B");
        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });
        jPanel2.add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 90, -1));

        LbB.setText("B:");
        jPanel2.add(LbB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 20, 24));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Phép toán:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, -1));

        txtPheptoan.setEditable(false);
        txtPheptoan.setBackground(new java.awt.Color(153, 153, 153));
        txtPheptoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPheptoan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPheptoan.setToolTipText("Hiển thị phép toán thực hiện");
        txtPheptoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPheptoanActionPerformed(evt);
            }
        });
        jPanel2.add(txtPheptoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 160, -1));
        txtPheptoan.getAccessibleContext().setAccessibleName("txtPheptoan");

        txtKq2.setEditable(false);
        txtKq2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtKq2.setToolTipText("Nghiệm 3");
        txtKq2.setEnabled(false);
        txtKq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKq2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtKq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 70, 30));

        txtKq1.setEditable(false);
        txtKq1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtKq1.setToolTipText("Nghiệm 2");
        txtKq1.setEnabled(false);
        txtKq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKq1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtKq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 70, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("x3:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("x1:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("x2:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        TxtSoNg.setEditable(false);
        TxtSoNg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSoNg.setToolTipText("Số nghiệm");
        TxtSoNg.setEnabled(false);
        jPanel2.add(TxtSoNg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 160, -1));

        txtKq3.setEditable(false);
        txtKq3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtKq3.setToolTipText("Nghiệm 4");
        txtKq3.setEnabled(false);
        txtKq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKq3ActionPerformed(evt);
            }
        });
        jPanel2.add(txtKq3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 70, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("x4:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, 10));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Chọn thao tác", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BXoa.setText("Xóa Trắng");
        BXoa.setToolTipText("Xóa bài làm");
        BXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BXoaActionPerformed(evt);
            }
        });
        jPanel3.add(BXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        BThoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BThoat.setText("Thoát");
        BThoat.setToolTipText("Thoát chương trình");
        BThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BThoatActionPerformed(evt);
            }
        });
        jPanel3.add(BThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 90, -1));

        Bptb2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bptb2.setText("PT bậc 2");
        Bptb2.setToolTipText("Máy tính phương trình bậc 2");
        Bptb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bptb2ActionPerformed(evt);
            }
        });
        jPanel3.add(Bptb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 90, -1));

        BAns.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BAns.setText("Ans");
        BAns.setToolTipText("Sử dụng lại kết quả nghiệm 1 để tính");
        BAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnsActionPerformed(evt);
            }
        });
        jPanel3.add(BAns, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 90, -1));

        BGiai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BGiai.setText("Giải");
        BGiai.setToolTipText("Xuất kết quả");
        BGiai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGiaiActionPerformed(evt);
            }
        });
        jPanel3.add(BGiai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, -1));

        Btinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btinh.setText("Tính");
        Btinh.setToolTipText("Máy tính cơ bản (2 hệ số)");
        Btinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtinhActionPerformed(evt);
            }
        });
        jPanel3.add(Btinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, -1));

        Bptb3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bptb3.setText("PT bậc 3");
        Bptb3.setToolTipText("Máy tính phương trình bậc 3");
        Bptb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bptb3ActionPerformed(evt);
            }
        });
        jPanel3.add(Bptb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 90, -1));

        Bluy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bluy.setText("Lũy thừa");
        Bluy.setToolTipText("Tính Lũy thừa A mũ B");
        Bluy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BluyActionPerformed(evt);
            }
        });
        jPanel3.add(Bluy, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 90, -1));

        Bcan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bcan.setText("Căn");
        Bcan.setToolTipText("Tính Căn bậc B của A");
        Bcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcanActionPerformed(evt);
            }
        });
        jPanel3.add(Bcan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, -1));

        Bptb4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bptb4.setText("PT bậc 4");
        Bptb4.setToolTipText("Máy tính phương trình bậc 3");
        Bptb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bptb4ActionPerformed(evt);
            }
        });
        jPanel3.add(Bptb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Author: Phan Minh Quân");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BXoaActionPerformed
        // TODO add your handling code here:
        DelText();
        DelKq();
        ControlKq(false);

    }//GEN-LAST:event_BXoaActionPerformed

    private void BThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BThoatActionPerformed

    private void Bptb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bptb2ActionPerformed
        // TODO add your handling code here:
        kt = 6;
        txtPheptoan.setText("Phương trình bậc 2");
        txtC.setEnabled(Boolean.TRUE);
        txtD.setEnabled(Boolean.FALSE);
        txtE.setEnabled(Boolean.FALSE);
        txtF.setEnabled(Boolean.FALSE);
        DelText();
        DelKq();
        ControlKq(false);
        ControlTinh(false);
    }//GEN-LAST:event_Bptb2ActionPerformed

    private void BAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnsActionPerformed
        // TODO add your handling code here:
        txtA.setText(String.valueOf(txtKq.getText()));
        DelKq();
        ControlKq(false);
    }//GEN-LAST:event_BAnsActionPerformed

    private void BtinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtinhActionPerformed
        // TODO add your handling code here:
        kt = 0;
        txtPheptoan.setText("");
        txtC.setEnabled(Boolean.FALSE);
        txtD.setEnabled(Boolean.FALSE);
        txtE.setEnabled(Boolean.FALSE);
        txtF.setEnabled(Boolean.FALSE);
        DelText();
        DelKq();
        ControlKq(false);
        ControlTinh(true);
    }//GEN-LAST:event_BtinhActionPerformed

    private void txtKqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKqActionPerformed

    private void BmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodActionPerformed
        // TODO add your handling code here:
        kt = 5;
        txtPheptoan.setText("%");
        DelKq();
    }//GEN-LAST:event_BmodActionPerformed

    private void BthuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthuongActionPerformed
        // TODO add your handling code here:
        kt = 4;
        txtPheptoan.setText("/");
        DelKq();
    }//GEN-LAST:event_BthuongActionPerformed

    private void BtichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtichActionPerformed
        // TODO add your handling code here:
        kt = 3;
        txtPheptoan.setText("*");
        DelKq();
    }//GEN-LAST:event_BtichActionPerformed

    private void BhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhieuActionPerformed
        // TODO add your handling code here:
        kt = 2;
        txtPheptoan.setText("-");
        DelKq();
    }//GEN-LAST:event_BhieuActionPerformed

    private void BtongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtongActionPerformed
        // TODO add your handling code here:
        kt = 1;
        txtPheptoan.setText("+");
        DelKq();
    }//GEN-LAST:event_BtongActionPerformed

    private void txtDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDActionPerformed

    private void txtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCActionPerformed

    private void txtEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEActionPerformed

    private void txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFActionPerformed

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBActionPerformed

    private void Bptb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bptb3ActionPerformed
        // TODO add your handling code here:
        kt = 7;
        txtPheptoan.setText("Phương trình bậc 3");
        txtC.setEnabled(Boolean.TRUE);
        txtD.setEnabled(Boolean.TRUE);
        txtE.setEnabled(Boolean.FALSE);
        txtF.setEnabled(Boolean.FALSE);
        DelText();
        DelKq();
        ControlKq(false);
        ControlTinh(false);
    }//GEN-LAST:event_Bptb3ActionPerformed

    private void BGiaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGiaiActionPerformed
        // TODO add your handling code here:
        
        //Diều khiển TextField Kết quả
        ControlKq(false);
        DelKq();
        
        if(kt < 6 || kt == 8 || kt == 9)
        {
            txtKq.setEnabled(true);
            //Tính Tổng
            if(kt == 1)
            {
                double a = Double.parseDouble(txtA.getText());
                double b = Double.parseDouble(txtB.getText());
                double Tong = a + b;
                txtKq.setText(String.valueOf(Tong));
            }
            //Tính Hiệu
            else if(kt == 2)
            {
                double a = Double.parseDouble(txtA.getText());
                double b = Double.parseDouble(txtB.getText());
                double Hieu = a - b;
                txtKq.setText(String.valueOf(Hieu));
            }
            //Tính Tích
            else if(kt == 3)
            {
                double a = Double.parseDouble(txtA.getText());
                double b = Double.parseDouble(txtB.getText());
                double Tich = a * b;
                txtKq.setText(String.valueOf(Tich));
            }
            //Tính Thương
            else if(kt == 4)
            {
                double a = Double.parseDouble(txtA.getText());
                double b = Double.parseDouble(txtB.getText());
                if(b == 0) 
                {
                    txtKq.setEnabled(false);
                    TxtSoNg.setText("Vui lòng nhập B khác 0");
                }
                else 
                {
                    double Thuong = a / b;
                    txtKq.setText(String.valueOf(Thuong));
                }
            }
            //Tính Thương lấy phần dư
            else if(kt == 5)
            {
                double a = Double.parseDouble(txtA.getText());
                double b = Double.parseDouble(txtB.getText());
                if(b == 0) 
                {
                    txtKq.setEnabled(false);
                    TxtSoNg.setText("Vui lòng nhập B khác 0");
                }
                else 
                {
                    double ThuongMod = a % b;
                    txtKq.setText(String.valueOf(ThuongMod));
                }
            }
            else if(kt == 8)
            {
                double a = Double.parseDouble(txtA.getText());
                double b = Double.parseDouble(txtB.getText());
                double Lt = pow(a, b);
                txtKq.setText(String.valueOf(Lt));
            }
            else if(kt == 9)
            {
                double a = Double.parseDouble(txtA.getText());
                double b = Double.parseDouble(txtB.getText());
                double Can = sqrtn(a, b);
                if(Can == Double.MAX_VALUE) 
                {
                    txtKq.setEnabled(false);
                    TxtSoNg.setText("Nhập lại B hoặc A > 0");
                }
                else 
                {
                    TxtSoNg.setText("");
                    txtKq.setText(String.valueOf(Can));
                }
            }
        }
        //Tính phương trình bậc 2
        else if(kt == 6)
        {
            double a = Double.parseDouble(txtA.getText());
            double b = Double.parseDouble(txtB.getText());
            double c = Double.parseDouble(txtC.getText());
            TxtSoNg.setEnabled(true);
            giaiptb2(a,b,c);
        }
        //Tính phương trình bậc 3
        else if(kt == 7)
        {
            double a = Double.parseDouble(txtA.getText());
            double b = Double.parseDouble(txtB.getText());
            double c = Double.parseDouble(txtC.getText());
            double d = Double.parseDouble(txtD.getText());
            TxtSoNg.setEnabled(true);
            if(a == 0) giaiptb2(b, c, d);
            else giaiptb3(a, b, c, d);
        }
        else if(kt == 10)
        {
            double a = Double.parseDouble(txtA.getText());
            double b = Double.parseDouble(txtB.getText());
            double c = Double.parseDouble(txtC.getText());
            double d = Double.parseDouble(txtD.getText());
            double e = Double.parseDouble(txtE.getText());
            if(a == 0 && b == 0) giaiptb2(c, d, e);
            else if(a == 0) giaiptb3(b, c, d, e);
            else giaiptb4(a, b, c, d, e);
        }
    }//GEN-LAST:event_BGiaiActionPerformed

    private void txtPheptoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPheptoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPheptoanActionPerformed

    private void txtKq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKq1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKq1ActionPerformed

    private void BluyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BluyActionPerformed
        // TODO add your handling code here:
        kt = 8;
        txtPheptoan.setText("Lũy thừa A mũ B");
        txtC.setEnabled(Boolean.FALSE);
        txtD.setEnabled(Boolean.FALSE);
        txtE.setEnabled(Boolean.FALSE);
        txtF.setEnabled(Boolean.FALSE);
        DelText();
        DelKq();
        ControlKq(false);
        ControlTinh(false);
    }//GEN-LAST:event_BluyActionPerformed

    private void BcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcanActionPerformed
        // TODO add your handling code here:
        kt = 9;
        txtPheptoan.setText("Căn bậc B của A");
        txtC.setEnabled(Boolean.FALSE);
        txtD.setEnabled(Boolean.FALSE);
        txtE.setEnabled(Boolean.FALSE);
        txtF.setEnabled(Boolean.FALSE);
        DelText();
        DelKq();
        ControlKq(false);
        ControlTinh(false);
    }//GEN-LAST:event_BcanActionPerformed

    private void Bptb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bptb4ActionPerformed
        // TODO add your handling code here:
        kt = 10;
        txtPheptoan.setText("Phương trình bậc 4");
        txtC.setEnabled(Boolean.TRUE);
        txtD.setEnabled(Boolean.TRUE);
        txtE.setEnabled(Boolean.TRUE);
        txtF.setEnabled(Boolean.FALSE);
        DelText();
        DelKq();
        ControlKq(false);
        ControlTinh(false);
    }//GEN-LAST:event_Bptb4ActionPerformed

    private void txtKq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKq3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKq3ActionPerformed

    private void txtKq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKq2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKq2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    //Hàm giải phương trình bậc 2
    public void giaiptb2(double a, double b, double c)
    {
        double d;
        double kq1, kq2;
        if(a!=0)
        {
            d = b*b - 4*a*c;
            if(d>0)
            {
                TxtSoNg.setText("Có 2 nghiệm");
                txtKq.setEnabled(true);
                txtKq1.setEnabled(Boolean.TRUE);
                kq1 =(-b-sqrt(d))/(2*a);
                kq2 = (-b+sqrt(d))/(2*a);
                if(abs(kq1) % 1 >= 0.9999999999)
                {
                    if(kq1 < 0) kq1 = (int)kq1 - 1;
                    else kq1 = (int)kq1 + 1;
                }
                if(abs(kq2) % 1 >= 0.9999999999)
                {
                    if(kq2 < 0) kq2 = (int)kq2 - 1;
                    else kq2 = (int)kq2 + 1;
                }
                txtKq.setText(String.valueOf(kq1));
                txtKq1.setText(String.valueOf(kq2));
            }
            else if(d==0)
            {
                TxtSoNg.setText("Có nghiệm kép");
                txtKq.setEnabled(true);
                kq1 =(-b+sqrt(d))/(2*a);
                if(abs(kq1) % 1 >= 0.9999999999)
                {
                    if(kq1 < 0) kq1 = (int)kq1 - 1;
                    else kq1 = (int)kq1 + 1;
                }
                txtKq.setText(String.valueOf(kq1));
            }
            else if(d<0) TxtSoNg.setText("Vô nghiệm");
        }
        else if(a==0 && b!=0)
        {
            TxtSoNg.setText("Có 1 nghiệm");
            txtKq.setEnabled(true);
            kq1 =(-c)/(b);
            if(kq1==-0) kq1 = 0;
            if(abs(kq1) % 1 >= 0.9999999999)
                {
                    if(kq1 < 0) kq1 = (int)kq1 - 1;
                    else kq1 = (int)kq1 + 1;
                }
            txtKq.setText(String.valueOf(kq1));
        }
        else if(a==0 && b==0 && c!=0)
        {
            TxtSoNg.setText("Vô nghiệm");
        }
        else if(a==0 && b==0 && c==0)
        {
            TxtSoNg.setText("Vô số nghiệm");
        }
    }
    //Hàm giải phương trình bậc 3
    public void giaiptb3(double a, double b, double c, double d)
    {
        double dt = b*b - 3*a*c;
        double k, kq, kq1, kq2;
        k = (9*a*b*c - 2*Math.pow(b,3) - 27*a*a*d)/(2*sqrt(pow(abs(dt),3)));
        
        if(dt > 0)
        {
            if(abs(k) <= 1)
            {
                TxtSoNg.setText("có 3 nghiệm (dt>0 & k<=1)");
                txtKq.setEnabled(true);
                txtKq1.setEnabled(true);
                txtKq2.setEnabled(true);
                kq = (2*sqrt(dt)*cos((acos(k))/3) - b) / (3*a);
                kq1 = (2*sqrt(dt)*cos((acos(k))/3 - 2*PI/3) - b) / (3*a);
                kq2 = (2*sqrt(dt)*cos((acos(k))/3 + 2*PI/3) - b) / (3*a);
                if(abs(kq) % 1 >= 0.9999999999)
                {
                    if(kq < 0) kq = (int)kq - 1;
                    else kq = (int)kq + 1;
                }
                if(abs(kq1) % 1 >= 0.9999999999)
                {
                    if(kq1 < 0) kq1 = (int)kq1 - 1;
                    else kq1 = (int)kq1 + 1;
                }
                if(abs(kq2) % 1 >= 0.9999999999)
                {
                    if(kq2 < 0) kq2 = (int)kq2 - 1;
                    else kq2 = (int)kq2 + 1;
                }
                txtKq.setText(String.valueOf(kq));
                txtKq1.setText(String.valueOf(kq1));
                txtKq2.setText(String.valueOf(kq2));
            }
            else
            {
                TxtSoNg.setText("có 1 nghiệm (dt>0 & k>1)");
                txtKq.setEnabled(true);
                kq = ((sqrt(dt)*abs(k))/(3*a*k))
                     * (pow((abs(k)) + sqrt(k*k - 1), 1.0/3)
                      + pow((abs(k)) - sqrt(k*k - 1), 1.0/3))
                       - (b /(3*a));
                if(abs(kq) % 1 >= 0.9999999999)
                {
                    if(kq < 0) kq = (int)kq - 1;
                    else kq = (int)kq + 1;
                }
                txtKq.setText(String.valueOf(kq));
            }
        }
        else if(dt == 0)
        {
            TxtSoNg.setText("có 1 nghiệm bội (dt==0)");
            txtKq.setEnabled(true);
            kq = ((-b) + (pow((pow(b,3) - 27*a*a*d), 1.0/3))) / (3*a);
            if(abs(kq) % 1 >= 0.9999999999)
                {
                    if(kq < 0) kq = (int)kq - 1;
                    else kq = (int)kq + 1;
                }
            txtKq.setText(String.valueOf(kq));
        }
        else if(dt < 0)
        {
            TxtSoNg.setText("có 1 nghiệm (dt<0)");
            txtKq.setEnabled(true);
            kq = (sqrt(abs(dt))/(3*a))
                     * (sqrtn(k + sqrt(k*k + 1), 3)
                      + sqrtn(k - sqrt(k*k + 1), 3))
                       - (b /(3*a));
            if(abs(kq) % 1 >= 0.9999999999)
                {
                    if(kq < 0) kq = (int)kq - 1;
                    else kq = (int)kq + 1;
                }
            txtKq.setText(String.valueOf(kq));
        }
    }
    //Hàm tính phương trình bậc 3 (lấy kết quả không in)
    public double tinhptb3(double a, double b, double c, double d)
    {
        double dt = b*b - 3*a*c;
        double k, kq = 0, kq1 = 0, kq2 = 0, da = 0;
        k = (9*a*b*c - 2*Math.pow(b,3) - 27*a*a*d)/(2*sqrt(pow(abs(dt),3)));
        
        if(dt > 0)
        {
            if(abs(k) <= 1)
            {
                kq = (2*sqrt(dt)*cos((acos(k))/3) - b) / (3*a);
                kq1 = (2*sqrt(dt)*cos((acos(k))/3 - 2*PI/3) - b) / (3*a);
                kq2 = (2*sqrt(dt)*cos((acos(k))/3 + 2*PI/3) - b) / (3*a);
            }
            else
            {
                kq = ((sqrt(dt)*abs(k))/(3*a*k))
                     * (pow((abs(k)) + sqrt(k*k - 1), 1.0/3)
                      + pow((abs(k)) - sqrt(k*k - 1), 1.0/3))
                       - (b /(3*a));
            }
        }
        else if(dt == 0)
        {
            kq = ((-b) + (pow((pow(b,3) - 27*a*a*d), 1.0/3))) / (3*a);
        }
        else if(dt < 0)
        {
            kq = (sqrt(abs(dt))/(3*a))
                     * (sqrtn(k + sqrt(k*k + 1), 3)
                      + sqrtn(k - sqrt(k*k + 1), 3))
                       - (b /(3*a));
        }
        if(abs(kq) % 1 >= 0.9999999999)
        {
            if(kq < 0) kq = (int)kq - 1;
            else kq = (int)kq + 1;
            return kq;
        }
        else if(abs(kq1) % 1 >= 0.9999999999)
        {
            if(kq1 < 0) kq1 = (int)kq1 - 1;
            else kq1 = (int)kq1 + 1;
            return kq1;
        }
        else if(abs(kq2) % 1 >= 0.9999999999)
        {
            if(kq2 < 0) kq2 = (int)kq2 - 1;
            else kq2 = (int)kq2 + 1;
            return kq2;
        }
        else return kq;
    }
    //Hàm giải phương trình bậc 4
    public void giaiptb4(double a, double b, double c, double d, double e)
    {
        double d1, d2, d3, d4;
        d1 = b / a;
        d2 = c / a;
        d3 = d / a;
        d4 = e / a;
        double x = d1 / 4;
        double A, B, C;
        A = 6 - 3*d1*x + d2;
        B = d1*d1*d1/8 - d2*d1/2 + d3;
        C = x*x*x*x - d1*x*x*x + d2*x*x - d3*x + d4;
        double m = tinhptb3(8, (-4)*A, (-8)*C, 4*A*C - B*B);
        double y1, y2, y3, y4;
        double M = sqrt(2*m - A);
        //Nghiệm phương trình phụ
        y1 = (0.5)*(M + (sqrt(((2*B)/(-M)) - 2*m - A)));
        y2 = (0.5)*(M - (sqrt(((2*B)/(-M)) - 2*m - A)));
        y3 = (0.5)*((-M) + (sqrt(((2*B)/M) - 2*m - A)));
        y4 = (0.5)*((-M) - (sqrt(((2*B)/M) - 2*m - A)));
        
        //Kiểm tra số nghiệm
        int n = -1;
        if(2*m - A < 0) n = 0;
        else if((((2*B)/M) - 2*m - A) < 0 && (((2*B)/(-M)) - 2*m - A) < 0) n = 1;
        else if((((2*B)/(-M)) - 2*m - A) < 0) n = 2;
        else if((((2*B)/M) - 2*m - A) < 0) n = 3;
        
        //Nghiệm phương trình chính
        double x1, x2, x3, x4;
        x1 = y1 - x;
        x2 = y2 - x;
        x3 = y3 - x;
        x4 = y4 - x;
        
        //Nghiệm chính thức (nghiệm đúng)
        TxtSoNg.setEnabled(true);
        if(n == 0 || n == 1) TxtSoNg.setText("Vô nghiệm");
        else if(n == 2 && n != 3) 
        {
            TxtSoNg.setText("có 2 nghiệm ");
            txtKq2.setEnabled(true);
            txtKq3.setEnabled(true);
            txtKq2.setText(String.valueOf(x3));
            txtKq3.setText(String.valueOf(x4));
        }
        else if(n == 3 && n != 2) 
        {
            TxtSoNg.setText("có 2 nghiệm");
            txtKq.setEnabled(true);
            txtKq1.setEnabled(true);
            txtKq.setText(String.valueOf(x1));
            txtKq1.setText(String.valueOf(x2));
        }
        else 
        {
            TxtSoNg.setText("có 4 nghiệm");
            txtKq.setEnabled(true);
            txtKq1.setEnabled(true);
            txtKq2.setEnabled(true);
            txtKq3.setEnabled(true);
            txtKq.setText(String.valueOf(x1));
            txtKq1.setText(String.valueOf(x2));
            txtKq2.setText(String.valueOf(x3));
            txtKq3.setText(String.valueOf(x4));
        }
    }
    //Hàm xóa các Hệ số đã nhập
    public void DelText()
    {
        txtA.setText("");
        txtB.setText("");
        txtC.setText("");
        txtD.setText("");
        txtE.setText("");
        txtF.setText("");
        TxtSoNg.setText("");
    }
    //Hàm xóa các kết quả đã tính
    public void DelKq()
    {
        txtKq.setText("");
        txtKq1.setText("");
        txtKq2.setText("");
        txtKq3.setText("");
    }
    //Hàm Enable/Disable các Phép tính cơ bản
    public void ControlTinh(boolean c)
    {
        Btong.setEnabled(c);
        Bhieu.setEnabled(c);
        Btich.setEnabled(c);
        Bthuong.setEnabled(c);
        Bmod.setEnabled(c);
    }
    //Hàm Enable/Disable Ô Kết quả và Số nghiệm
    public void ControlKq(boolean c)
    {
        txtKq.setEnabled(c);
        txtKq1.setEnabled(c);
        txtKq2.setEnabled(c);
        txtKq3.setEnabled(c);
        TxtSoNg.setEnabled(c);
    }
    //Hàm tính Căn bậc n của x (Gồm 3 hàm)
    public double _exp(double x) //Ham exp^x
    {
        double s = 0, temp = 1;
        int k = 0;
        while (s != s + temp)
        {
            s += temp;
            k++;
            temp *= x/k;
        }
        return s;
    }

    public double _log(double x) //Hàm ln(1 + x)
    {
        x = x - 1;
        if (-1 < x && x <= 1)
        {
            double s = 0, temp = x;
            int k = 0;
            while (s != s + temp)
                {
                    s += temp;
                    k++;
                    temp *= -x*k/(k+1);
                }
            return s;
        }
        else return _log(1 + 1/x) - _log(1/x);
    }

    public double sqrtn(double x, double n) //Hàm căn bậc n của x
    {
        if (x == 0) return 0;
        else
            if (n%2 != 0)
                if (x > 0) return _exp(_log(x)/n);
                else return -_exp(_log(-x)/n);
            else
                if (x > 0) return _exp(_log(x)/n);
                else return Double.MAX_VALUE;
    }

    public void ControlPheptoan(boolean c)
    {
        Bluy.setEnabled(c);
        Bcan.setEnabled(c);
        Bptb2.setEnabled(c);
        Bptb3.setEnabled(c);
        Bptb4.setEnabled(c);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAns;
    private javax.swing.JButton BGiai;
    private javax.swing.JButton BThoat;
    private javax.swing.JButton BXoa;
    private javax.swing.JButton Bcan;
    private javax.swing.JButton Bhieu;
    private javax.swing.JButton Bluy;
    private javax.swing.JButton Bmod;
    private javax.swing.JButton Bptb2;
    private javax.swing.JButton Bptb3;
    private javax.swing.JButton Bptb4;
    private javax.swing.JButton Bthuong;
    private javax.swing.JButton Btich;
    private javax.swing.JButton Btinh;
    private javax.swing.JButton Btong;
    private javax.swing.JLabel LbA;
    private javax.swing.JLabel LbA3;
    private javax.swing.JLabel LbB;
    private javax.swing.JLabel LbC;
    private javax.swing.JLabel LbE;
    private javax.swing.JLabel LbF;
    private javax.swing.JLabel LbKq;
    private javax.swing.JTextField TxtSoNg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtE;
    private javax.swing.JTextField txtF;
    private javax.swing.JTextField txtKq;
    private javax.swing.JTextField txtKq1;
    private javax.swing.JTextField txtKq2;
    private javax.swing.JTextField txtKq3;
    private javax.swing.JTextField txtPheptoan;
    // End of variables declaration//GEN-END:variables
}
